kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apt-cacher-ng
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  
